server:
  port: 8091
  servlet:
    context-path: /arslinth-api

spring:
  datasource:
    url: jdbc:mysql://114.132.242.83:3306/arslinth-boot?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: ENC(MAgCq7JTlPnFLtdzzY4Luc3Mr77N3I28/PO2mMIPIecGZQu+32fgnQh1Rwd8xlcd)
    password: ENC(VGTlPiXxcPB6hobqjgQVGzr1Swo76/1j2f6f1eRuXrDDiiqUsA4eJHDVNZQb3T/1)
  redis:
    password:
    database: 1

logging:
  config: classpath:log4j2/log4j2-spring-dev.xml

file:
  #图片上传真实路径
  imgFolder: C:/Users/Arslinth/Pictures/btxc-archives/
  #上传文件的真实路径
  uploadFolder: C:/Users/Arslinth/Documents/北投项目/ftpDownload/file/upload/

jasypt:
  encryptor:
    password: springsteam0117