server:
  port: 8090
  servlet:
    context-path: /archives-api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/btxc-archives?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: archives123
  redis:
    password:
    database: 0

logging:
  config: classpath:log4j2/log4j2-spring-prod.xml

file:
  #图片上传保存地址
  localImgFolder: D:/javaweb/environment-prod/pictures/
  localZipFolder: D:/ftpService/file/
  uploadFolder: D:/ftpService/upload/

ftp:
  config:
    #OA系统文件导出地址
    localPath: D:/ftpService/

IDTrust-base-url: https://idtrust.bgigc.com:4433

IDTrust-redirect-uri: http://10.0.22.62/archives/login

IDTrust:
  client-id: 342564677
  client-secret: c4da65892a907dce081ea093d1534902

##统一登入参数
#IDTrust-base-url: https://10.0.1.97:4433
##回调地址
#IDTrust-redirect-uri: http://10.0.22.62/archives/login
#
#IDTrust:
#  client-id: 4000619997
#  client-secret: 6d084f370e72994a265dca225ba93616
