server:
  port: 8090
  servlet:
    context-path: /archives-api

spring:
  datasource:
    url: jdbc:mysql://10.0.22.62:3306/btxc-archives?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: btxc-archives
    password: archives123
  redis:
    password:
    database: 0

logging:
  config: classpath:log4j2/log4j2-spring-prod.xml

file:
  localImgFolder: /javaweb/uploadPath/
  localZipFolder: /FTP/file/
  uploadFolder: /javaweb/upload/

ftp:
  config:
    #OA系统文件导出地址
    localPath: /FTP/



IDTrust-base-url: https://idtrust.bgigc.com:4433

#IDTrust-redirect-uri: http://10.0.22.62/archives/login
IDTrust-redirect-uri: http://221.7.214.83:38094/archives/login

IDTrust:
  client-id: 342564677
  client-secret: c4da65892a907dce081ea093d1534902